rust-vmm/linux-loader

- src/loader/mod.rs
The method GuestMemory::end_addr() was renamed.
Signed-off-by: Rob Bradford <robert.bradford@intel.com>
> loader: Update for latest vm-memory changes

- coverage_config_aarch64.json
- coverage_config_x86_64.json
- src/configurator/aarch64/fdt.rs
- src/configurator/aarch64/mod.rs
- src/configurator/mod.rs
- src/configurator/x86_64/linux.rs
- src/configurator/x86_64/mod.rs
- src/configurator/x86_64/pvh.rs
- src/lib.rs
- src/loader/aarch64/pe/mod.rs
- src/loader/mod.rs
- src/loader/x86_64/bzimage/mod.rs
- src/loader/x86_64/elf/mod.rs
#15 
This PR introduces a new `configurator` module, meant to build (TBD) and write (included in this PR) boot parameters in guest memory. To begin with, the VMM will have to build its own boot params, encapsulate them into [`ByteValued`](https://docs.rs/vm-memory/0.2.0/vm_memory/bytes/trait.ByteValued.html) objects, then pass them on to `linux-loader`.
VMM workflow:
```rust
let load_result = kernel_loader.load<ReadImpl, GuestMemoryImpl>(
guest_memory,
kernel_start_addr,
kernel_image,
himem_start_addr
)?;
let (boot_params_header, boot_params_sections): (HeaderImpl, Vec<SectionImpl>) = Vmm::build_boot_params()?;
BootConfiguratorImpl::write_bootparams::<HeaderImpl, SectionImpl, GuestMemoryImpl>(
(boot_params_header, header_addr),
Some((boot_params_sections, sections_addr)),
guest_memory
)?; …
```
> Boot configurator: trait (and associated objects) that write boot params in guest memory

- coverage_config_aarch64.json
- coverage_config_x86_64.json
- src/cmdline/mod.rs
- src/lib.rs
- src/loader/mod.rs
> Usage examples, doctests & cosmetic tweaks

- coverage_config_aarch64.json
- coverage_config_x86_64.json
- src/loader/aarch64/pe/mod.rs
- src/loader/mod.rs
- src/loader/x86_64/bzimage/mod.rs
- src/loader/x86_64/elf/mod.rs
As part of the discussion in #12, we have noticed that the `kernel_start` parameter has different usages in the implementations for `PE`, `Elf`, and `BzImage`. The `Elf` implementation is specially confusing, since `kernel_start` is used to specify an offset to add to the default load address of the kernel. The discussion is ongoing to determine whether this has any real use cases or provides any security benefits.
In the meantime, I propose to rename the parameter to `kernel_offset`, which might be more appropriate to describe its usage by the implementers of `KernelLoader`.
Also, since PVH code expects the kernel to be loaded at its default load address, it cannot be used to boot guests if a non-default load address is requested by using the `kernel_offset` argument. If `kernel_offset` …
> Clarify uses of kernel_start parameter

- coverage_config_x86_64.json
- src/cmdline/mod.rs
- src/configurator/aarch64/fdt.rs
- src/configurator/mod.rs
- src/configurator/x86_64/linux.rs
- src/configurator/x86_64/pvh.rs
- src/loader/aarch64/pe/mod.rs
- src/loader/mod.rs
- src/loader/x86_64/bzimage/mod.rs
- src/loader/x86_64/elf/mod.rs
All Error enumerations except cmdline::Error have implemented
std::error::Error, so add the missing one.
Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>
Please refer to #35 for more information.
> cmdline: implement std::error::Error for Error

- .buildkite/bench_pipeline.yml
- .buildkite/hooks/post-checkout
- .buildkite/pipeline.yml
- Cargo.toml
- benches/aarch64/mod.rs
- benches/main.rs
- benches/x86_64/mod.rs
- coverage_config_aarch64.json
- coverage_config_x86_64.json
- src/configurator/aarch64/fdt.rs
- src/configurator/mod.rs
- src/configurator/x86_64/linux.rs
- src/configurator/x86_64/pvh.rs
- src/loader/x86_64/bzimage/mod.rs
The first commit is a subset of #43, with an additional commit adding benchmarks for the bzImage loading functionality (and showcasing how to benchmark feature-gated functions).
This PR is part of a larger story of adding performance tests to rust-vmm crates and running them automatically. See https://github.com/rust-vmm/rust-vmm-ci/issues/24.
To automatically run these tests in the `linux-loader` crate, the following PRs need to be merged in this order:
1. This PR
1. https://github.com/rust-vmm/rust-vmm-container/pull/28
1. https://github.com/rust-vmm/rust-vmm-ci/pull/25
1. TODO: PR in `linux-loader` that replicates https://github.com/rust-vmm/linux-loader/pull/43/commits/6ceda5b62c8fefa726eb285a2d8df0cee075b0a3 - custom Buildkite pipeline that uses the new container and runs the new …
> Add benchmark tests for publicly exposed functions

- .buildkite/bench_pipeline.yml
- Cargo.toml
This prevents Unicode encoding errors when printing to `stdout` from the benchmark integ test and stabilizes `criterion` output.
> Force UTF-8 encoding in custom pipeline and block criterion version

- CHANGELOG.md
- coverage_config_x86_64.json
- src/cmdline/mod.rs
This PR extends the `Cmdline` with the possibility of specifying serial console and virtio MMIO device configurations, which are transparently stringified and appended to the command line.
> Specify serial console & virtio MMIO devices to the kernel command line

- .buildkite/download_resources.sh
- .buildkite/hooks/post-checkout
- Cargo.toml
- build.rs
This PR removes the buildkite hooks and makes it possible to run the unit tests on local dev machines as well by downloading the required resources for running the test as part of a rust build script.
> Run unit tests on local dev machines

- coverage_config_x86_64.json
- src/loader/x86_64/elf/mod.rs
In response to #66.
* While using `aling_up` we're converting the function result
to other data types. The conversions were double checked and
comments were added to clarify why they are safe.
> elf: `align_up` usage susceptible to data loss

- docs/TESTING.md
- src/loader/mod.rs
> src/loader: use Cmdline instead CStr in load_cmdline()

- coverage_config_x86_64.json
- src/cmdline/mod.rs
> Implement `Debug` and `PartialEq` for `CmdLine`

- Cargo.toml
Use caret requirements for dependencies.
Fixes: rust-vmm/community#131
Signed-off-by: wanglei01 <wllenyj@linux.alibaba.com>
requirements:
test.
> update dependency requirements

- src/cmdline/mod.rs
- src/loader/mod.rs
Changing as_str() into as_cstr() in order to retrieve a null terminated string from the Cmdline struct.
Signed-off-by: Traistaru Andrei Cristian <atc@amazon.com>
requirements:
test.
> Changing as_str into as_cstr

- CHANGELOG.md
- Cargo.toml
Details in the CHANGELOG.
**NOTE**: once we publish the new version I will yank v0.4.0 and v0.5.0 because of a critical bug in the way we're loading the kernel command line into guest memory. The 2 aforemntioned releases do not write a null terminator at the end of the command line which means that the kernel might end up reading past the intended command line size. This is typically not the case in a common VMM scenario because the Guest Memory is typically zeroed, so we do get a null terminated command line by luck.
requirements:
test.
> release v0.6.0

- src/loader/x86_64/bzimage/mod.rs
Replace access to unaligned reference in bzImage tests with std::ptr::addr_of macro and `read_unaligned` method.
Fixes: https://github.com/rust-vmm/linux-loader/issues/123
requirements:
- [] All added/changed functionality has a corresponding unit/integration
test.
- [] Any newly added `unsafe` code is properly documented.
> Remove access to unaligned refs from bzImage tests

- CHANGELOG.md
- Cargo.toml
Requires so that downstream crates can consume the vm-memory update.
Bumps the crate version to 0.9.0
requirements:
test.
> Prepare Release 0.9.0

- .buildkite/download_resources.sh
- Cargo.toml
- src/loader/x86_64/bzimage/mod.rs
The integ tests used to download a 4.9 kernel image from the Debian servers, which has been since taken down. Updating to a 5.10 image and adjusting the tests accordingly.
Fixes #149
requirements:
test.
> Update bzimage kernel image download path

- CHANGELOG.md
- Cargo.toml
- src/cmdline/mod.rs
- src/lib.rs
- src/loader/mod.rs
* Build docs.rs documentation with features enabled, since they do not show up at the moment.
* Fix rustdoc warnings about bare URLs.
* Fix rustdoc warnings about invalid HTML tags.
requirements:
- `N/A` All added/changed functionality has a corresponding unit/integration
test.
- `N/A` Any newly added `unsafe` code is properly documented.
> Build docs.rs documentation with features enabled and other fixes

- benches/main.rs
- benches/x86_64/mod.rs
The `criterion_benchmark_nop` function does literally nothing, there is no need to run these benchs.
Re-organize the code to run `benches_bzimage` on x86 and x86_64 machines with `bzimage` feature enabled.
requirements:
`git commit -s`), and the commit message has max 60 characters for the
summary and max 75 characters for each description line.
test.
> aarch64: Remove redundant bench

- CHANGELOG.md
- Cargo.toml
linux-loader 0.13.0 incorporates:
- Introduce RISC-V64 architecture support.
- Updated vm-memory to 0.16.0.
- Re-organize `loader`, `configurator` and `benches` module layout, leaving original interface intact.
requirements:
`git commit -s`), and the commit message has max 60 characters for the
summary and max 75 characters for each description line.
test.
> chore: Prepare 0.13.0 release

- CHANGELOG.md
- src/cmdline/mod.rs
According to linux kernel document, the value of command line parameter can contains spaces (with double quotes) or equals.
requirements:
test.
> Fixing kernel commandline parameter validation

- src/loader/pe/mod.rs
This header is equivalent to the boot_params header found at the top of x86 kernels. We want to make this struct public to use it in a [fw_cfg implementation](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/7117#discussion_r2165060590) that reads the kernel header for both arm and x86
> loader: Make arm64_image_header public

- .github/workflows/release.yml
Add a trusted publishing workflow for crates.io. It will be triggered everytime there's a push of a tag starting with `v`.
The workflow must be manually added to crates.io:
> Configuring Trusted Publishing
>
> Configure your crate on crates.io:
>
>     Go to your crate's Settings → Trusted Publishing
>     Click the "Add" button and fill in:
>         Repository owner: Your GitHub username or organization
>         Repository name: The name of your repository
>         Workflow filename: The filename of your GitHub Actions workflow (e.g., "release.yml")
>         Environment: Optional environment name if you're using GitHub environments
>     Save the configuration
Documentation: https://crates.io/docs/trusted-publishing
cc @roypat 
Before submitting your PR, please make sure you …
> ci: add crates.io publish workflow
