rust-vmm/linux-loader

.buildkite/hooks/post-checkout, src/cmdline/mod.rs
The 4.9.0-9 kernel is no longer available.
=> Fix bzImage tests

.buildkite/hooks/post-checkout, Cargo.toml, src/loader/mod.rs
Update for latest vm-memory and fix the download location for the kernel.
=> Fix the unit tests

coverage_config_x86_64.json, src/cmdline/mod.rs, src/lib.rs
=> Simple Fixes examples in src/lib.rs and clippy warnings. 

CHANGELOG.md, Cargo.toml
For details about this release please check the CHANGELOG.md file.
=> release v0.4.0

.buildkite/custom-tests.json, src/configurator/mod.rs, src/configurator/x86_64/pvh.rs
If you want to use cmdline loader only, you can run build it with
--no-default-features
Signed-off-by: uran0sH <huangwenyuu@outlook.com>
requirements:
=> Make --no-default-features work 

CHANGELOG.md, Cargo.toml
See CHANGELOG.md file for details.
Signed-off-by: wanglei01 <wllenyj@linux.alibaba.com>
requirements:
test.
=> release v0.5.0 

Cargo.toml
Signed-off-by: Obei Sideg <obei.sideg@gmail.com>
Upgrade to 2021 edition
requirements:
test.
=> Upgrade to 2021 edition

src/cmdline/mod.rs, src/configurator/aarch64/fdt.rs, src/configurator/mod.rs, src/configurator/x86_64/linux.rs, src/configurator/x86_64/pvh.rs, src/loader/aarch64/pe/mod.rs, src/loader/mod.rs, src/loader/x86_64/bzimage/mod.rs, src/loader/x86_64/elf/mod.rs
Manually update rust-vmm-ci as we need the benchmark test fix to be able to merge the Rust version update.
This PR makes #113 obsolete.
requirements:
test.
=> Update rust vmm ci

CHANGELOG.md, coverage_config_x86_64.json, src/cmdline/mod.rs, src/loader/mod.rs
Reworking the Cmdline to leverage handling of boot args and init args. This PR should solve the #116 issue.
requirements:
test.
=> Cmdline refactoring

CHANGELOG.md, Cargo.toml
The new version of the linux-loader offers support for init arguments handling in Cmdline. Details in the CHANGELOG.
requirements:
test.
=> release v0.7.0

.buildkite/bench-tests.json, CHANGELOG.md, Cargo.toml, benches/aarch64/mod.rs, src/configurator/aarch64/fdt.rs, src/configurator/mod.rs, src/configurator/x86_64/pvh.rs, src/lib.rs, src/loader/aarch64/pe/mod.rs, src/loader/mod.rs, src/loader/x86_64/elf/mod.rs
See https://github.com/rust-vmm/community/issues/136
requirements:
test.
=> Update vm-memory + release

src/loader/x86_64/elf/mod.rs
Using rewind instead of seek to start
=> Using rewind instead of seek to start

CODEOWNERS, Cargo.toml
The github handles must start with @. Also have them on a single line like we do in the other rust-vmm repositories.
Fix: #131 
requirements:
test.
=> fix codeowners file

src/loader/aarch64/pe/mod.rs
Address issue from updated clippy - using .rewind(). This allows
rust-vmm-ci update.
requirements:
test.
=> loader: aarch64: pe: Use .rewind()

src/loader/x86_64/elf/mod.rs
Supplements https://github.com/rust-vmm/linux-loader/pull/142 with the needed code adjustments to appease clippy.
requirements:
test.
=> build(deps): bump rust-vmm-ci from `c2f8c93` to `8627b37`

CHANGELOG.md, Cargo.toml
- Update vm-memory to 0.12.2
- Prepare release 0.9.1
requirements:
test.
=> Release 0.9.1

CHANGELOG.md, Cargo.toml
Preparations for releasing 0.10.0 to crates.io, so that dependents can consume transitive dependency update vm-memory 0.13.0
requirements:
test.
=> chore: Prepare 0.10.0 release

CHANGELOG.md, Cargo.toml
=> chore: Prepare 0.11.0 release

CHANGELOG.md, Cargo.toml
requirements:
`git commit -s`), and the commit message has max 60 characters for the
summary and max 75 characters for each description line.
test.
=> chore: Prepare 0.12.0 release

Cargo.toml
- build: Update vm-memory from 0.15.0 to 0.16.0
requirements:
`git commit -s`), and the commit message has max 60 characters for the
summary and max 75 characters for each description line.
test.
=> build: Update vm-memory from 0.15.0 to 0.16.0
